CREATE TABLE USER(
	USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(128) NOT NULL UNIQUE,
	PASSWORD VARCHAR(128) 
);

CREATE TABLE AUTH_USER_GROUP(
	AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(128) NOT NULL,
	AUTH_GROUP VARCHAR(128) NOT NULL,
	CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
	UNIQUE (USERNAME,AUTH_GROUP)
);

CREATE TABLE CATEGORY(
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(128) NOT NULL
);

CREATE SEQUENCE POST_SEQUENCE;
alter sequence POST_SEQUENCE restart with 1;
CREATE TABLE POST(
	POST_ID BIGINT default post_sequence.nextval PRIMARY KEY,
--	POST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(128) NOT NULL,
	CONTENT VARCHAR(20000),
	CATEGORY_ID INT NOT NULL,
	DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT CATEGORY_POST_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
	UNIQUE (POST_ID,TITLE)
);